In [2]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.metrics import r2_score

In [3]:
data = pd.read_csv(r"C:\Users\Raviteja\Downloads\car-mpg.csv")
data.head()

,mpg,cyl,disp,hp,wt,acc,yr,origin,car_type,car_name
0,18.0,8,307.0,130,3504,12.0,70,1,0,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,0,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,0,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,0,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,0,ford torino

In [4]:
data.describe()

,mpg,cyl,disp,wt,acc,yr,origin,car_type
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864,0.530151
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055,0.499718
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000,0.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000,0.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000,1.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000,1.000000

In [7]:
data.columns

Index(['mpg', 'cyl', 'disp', 'hp', 'wt', 'acc', 'yr', 'origin', 'car_type',
       'car_name'],
      dtype='object')

In [8]:
data=data.drop(['car_name'],axis=1)

In [9]:
data

      mpg  cyl   disp   hp    wt   acc  yr  origin  car_type
0    18.0    8  307.0  130  3504  12.0  70       1         0
1    15.0    8  350.0  165  3693  11.5  70       1         0
2    18.0    8  318.0  150  3436  11.0  70       1         0
3    16.0    8  304.0  150  3433  12.0  70       1         0
4    17.0    8  302.0  140  3449  10.5  70       1         0
..    ...  ...    ...  ...   ...   ...  ..     ...       ...
393  27.0    4  140.0   86  2790  15.6  82       1         1
394  44.0    4   97.0   52  2130  24.6  82       2         1
395  32.0    4  135.0   84  2295  11.6  82       1         1
396  28.0    4  120.0   79  2625  18.6  82       1         1
397  31.0    4  119.0   82  2720  19.4  82       1         1

[398 rows x 9 columns]

In [11]:
data['origin']=data['origin'].replace({1:'america',2:'europe',3:'asia'})

In [12]:
data

      mpg  cyl   disp   hp    wt   acc  yr   origin  car_type
0    18.0    8  307.0  130  3504  12.0  70  america         0
1    15.0    8  350.0  165  3693  11.5  70  america         0
2    18.0    8  318.0  150  3436  11.0  70  america         0
3    16.0    8  304.0  150  3433  12.0  70  america         0
4    17.0    8  302.0  140  3449  10.5  70  america         0
..    ...  ...    ...  ...   ...   ...  ..      ...       ...
393  27.0    4  140.0   86  2790  15.6  82  america         1
394  44.0    4   97.0   52  2130  24.6  82   europe         1
395  32.0    4  135.0   84  2295  11.6  82  america         1
396  28.0    4  120.0   79  2625  18.6  82  america         1
397  31.0    4  119.0   82  2720  19.4  82  america         1

[398 rows x 9 columns]

In [14]:
data=pd.get_dummies(data,columns=['origin'],dtype=int)

In [15]:
data = data.replace('?',np.nan)

In [17]:
data =data.apply(pd.to_numeric,errors='ignore')

/tmp/ipykernel_1304/3959394043.py:1: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  data =data.apply(pd.to_numeric,errors='ignore')

In [19]:
#fill median only for numeric values
data=data.apply(lambda x:x.fillna(x.median()) if x.dtype != 'object' else x,axis=0)

In [20]:
data.head()

,mpg,cyl,disp,hp,wt,acc,yr,car_type,origin_america,origin_asia,origin_europe
0,18.0,8,307.0,130.0,3504,12.0,70,0,1,0,0
1,15.0,8,350.0,165.0,3693,11.5,70,0,1,0,0
2,18.0,8,318.0,150.0,3436,11.0,70,0,1,0,0
3,16.0,8,304.0,150.0,3433,12.0,70,0,1,0,0
4,17.0,8,302.0,140.0,3449,10.5,70,0,1,0,0

In [22]:
x=data.drop( ['mpg'],axis=1)
y=data[['mpg']]

In [23]:
x.head()

,cyl,disp,hp,wt,acc,yr,car_type,origin_america,origin_asia,origin_europe
0,8,307.0,130.0,3504,12.0,70,0,1,0,0
1,8,350.0,165.0,3693,11.5,70,0,1,0,0
2,8,318.0,150.0,3436,11.0,70,0,1,0,0
3,8,304.0,150.0,3433,12.0,70,0,1,0,0
4,8,302.0,140.0,3449,10.5,70,0,1,0,0

In [24]:
y.head()

    mpg
0  18.0
1  15.0
2  18.0
3  16.0
4  17.0

In [26]:
x_s=preprocessing.scale(x)